import type { Metadata } from "next";
import { VT323, Kiwi_Maru } from "next/font/google";
import "./globals.css";

const vt323 = VT323({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-vt323",
});

const kiwiMaru = Kiwi_Maru({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-kiwi-maru",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${vt323.variable} ${kiwiMaru.variable}`}>
        {children}
      </body>
    </html>
  );
}
